# Generated by Django 4.0.5 on 2022-07-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_rename_agendamentos_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='hora_agendada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
