# Generated by Django 4.0.5 on 2022-07-02 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_agendamento_data_agendada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
