version: "3.8"

services: # Lista os serviços a serem executados no Docker
  django-server: # Nome do servidor web do django
    build: . # Cria imagem com parametros definidos no Dockerfile no diretório atual
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000" # Comandos python para serem executados ao subir o servidor
    volumes: 
      - .:/code # Sincroniza todos os arquivos do projeto para o diretório /code no container

    ports: # Mapeamento da porta local para a porta do container
      - 8000:8000 # Porta padrão do django
      
    networks: # Define a network a ser utilizada
      - db_network

    depends_on: 
      - db-server # Possui dependencia do serviço db

  db-server: # Define um nome para o serviço
    image: postgres # Banco de dados usando imagem do postgres

    ports: # Mapeamento da porta local do PC para a porta do container
      - 5432:5432 # Porta padrão do postgres

    environment: # Declaração de variáveis de ambientes a serem utilizadas no serviço
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    networks: # Define a network a ser utilizada
      - db_network

    volumes: # Volume/diretório compartilhado com o container para persistir os dados
      - postgres_data:/var/lib/postgresql/data/
    
volumes: # Declaração do volume a ser utilizado para salvar permanente os dados do banco de dados postgres
  postgres_data:

networks: # Declaração de network a ser utilizada nos serviços
  db_network:
    driver: bridge